sudo: required
services:
  - docker

stages:
  - name: init
      - docker build -t djagielo/agilla-service -f ./ci/Dockerfile.dev .
  - name: test
      - docker run djagielo/agilla-service mvn clean test
  - name: deploy
    if: branch = master
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - docker build -t djagielo/agilla-service -f ./ci/Dockerfile