sudo: required
services:
  - docker

before_install:
  - docker build -t djagielo/agilla-service -f ./ci/Dockerfile.dev .

script:
  - docker run djagielo/agilla-service mvn clean test

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t djagielo/agilla-service -f ./ci/Dockerfile

deploy:
  provider: script
  script: docker push "djagielo/agilla-service:latest"
  on:
    branch: master
